spring:
  config:
    activate:
      on-profiles: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3307/webbanhang_db
    username: root
    password: admin123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  openapi:
    service:
      api-docs: backend-service
      server: http://localhost:${server.port}
      title: Backend service
      version: 1.0.0

jwt:
  secretKey: abc@123